### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by LucasLeandro1204** [muunapp/muun#1]
Are in your mind to use [vue-i18n](https://github.com/kazupon/vue-i18n)? If so, I can implement it =)

**Comment by Meadowcottage** [comment]
Plan is to eventually add [vue-i18n](https://github.com/kazupon/vue-i18n) support yes,
Currently however it is lower on the priority list 😛

**Comment by Meadowcottage** [comment]
Am slowly adding list of TODO and concepts of things to add to the organisation [project list](https://github.com/muunapp/muun/projects/1). 😄

**Comment by Meadowcottage** [comment]
Welp, this is now added. Thanks to @pixeldesu ❤️
